allow multiple windows symlinks per program

diff --git a/install b/install
--- a/install
+++ b/install
@@ -62,38 +62,40 @@ readonly DISTRO_NAME='Ubuntu'
 # List of files to be linked in WSL
 readonly WSL_DOTFILES="${SHARED_DOTFILES} wsl"
 
-# Files that must be linked in windows
+# Files that must be linked in windows filesystem
 readonly WINDOWS_DOTFILES="windows-terminal"
 
-# Create a windows symlink for use with windows programs
+# Create a windows filesystem symlink for use with windows programs
 # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/mklink
-make_windows_symlink(){
-    # Get metadata from metadata file
-    local link_name=$(cut -f1 -d, "${DOTS}/${1}/${META}")
-    local link_parent="/mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER}/$(cut -f2 -d, "${DOTS}/${1}/${META}")"
+make_windows_symlinks(){
+    while read -r line; do
+        local link_name=$(echo "${line}" | cut -f1 -d,)
+        # Windows symlink paths must be relative to windows user home folder
+        local link_parent="/mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER}/$(echo "${line}" | cut -f2 -d,)"
 
-    # Skip file if it is in backup
-    [ $skip_existing ] && [ -e "${OLD}/${1}/${link_name}" ] && { echo "➖ ${1}/${link_name} is already linked, skipping"; return 0; }
+        # # Skip file if it is in backup
+        [ $skip_existing ] && [ -e "${OLD}/${1}/${link_name}" ] && { echo "➖ ${1}/${link_name} is already linked, skipping"; continue; }
 
-    if [ -d "${link_parent}" ]; then
-        # Backup if normal file (cant parse windows symlink), otherwise must remove since mklink can't overwrite
-        if [ -f "${link_parent}/${link_name}" ]; then
-            [ -d "${OLD}/${1}" ] || { echo "Creating backup folder ${OLD}/${1}"; mkdir -p "${OLD}/${1}"; }
-            mv -f "${link_parent}/${link_name}" "${OLD}/${1}/${link_name}"
-        else
-            rm -f "${link_parent}/${link_name}"
+        if [ -d "${link_parent}" ]; then
+            # Backup if normal file (cant parse windows symlink), otherwise must remove since mklink can't overwrite
+            if [ -f "${link_parent}/${link_name}" ]; then
+                [ -d "${OLD}/${1}" ] || { echo "Creating backup folder ${OLD}/${1}"; mkdir -p "${OLD}/${1}"; }
+                mv -f "${link_parent}/${link_name}" "${OLD}/${1}/${link_name}"
+            else
+                rm -f "${link_parent}/${link_name}"
+            fi
+
+            # Create windows compatible paths for symlink
+            local link="${WINDOWS_DRIVE}:\\Users\\${WINDOWS_USER}\\$(cut -f2 -d, "${DOTS}/${1}/${META}" | tr '/' '\\')\\${link_name}"
+            local target="\\\\wsl\$\\${DISTRO_NAME}$(echo "${DOTS}/${1}/${link_name}" | tr '/' '\\')"
+
+            # Create symlink using cmd.exe
+            cmd.exe /c "mklink ${link} ${target}" 2>> ${LOG}
+            [ $? -ne 0 ] && echo "❌ Unable to create symlink for ${1}/${link_name}. Does cmd have admin rights?"
+        else 
+            echo "❌ ${link_parent} does not exist. Is ${1} installed?"
         fi
-
-        # Create windows compatible paths for symlink
-        local link="${WINDOWS_DRIVE}:\\Users\\${WINDOWS_USER}\\$(cut -f2 -d, "${DOTS}/${1}/${META}" | tr '/' '\\')\\${link_name}"
-        local target="\\\\wsl\$\\${DISTRO_NAME}$(echo "${DOTS}/${1}/${link_name}" | tr '/' '\\')"
-
-        # Create symlink using cmd.exe
-        cmd.exe /c "mklink ${link} ${target}" 2>> ${LOG}
-        [ $? -ne 0 ] && echo "❌ Unable to create symlink for ${1}/${link_name}. Does cmd have admin rights?"
-    else 
-        echo "❌ ${link_parent} does not exist. Is ${1} installed?"
-    fi
+    done < "${DOTS}/${1}/${META}"
 }
 
 setup_wsl() {
@@ -126,7 +128,7 @@ setup_wsl() {
     ln -sf "/mnt/${WINDOWS_DRIVE}/Users/${WINDOWS_USER}" "${WINDOWS_LINK}"
 
     for folder in ${WINDOWS_DOTFILES}; do
-        make_windows_symlink $folder
+        make_windows_symlinks $folder
     done
 
     for folder in ${WSL_DOTFILES}; do
